### ISSUE TITLE
Breakage when POSTGRES_DB is provided (and different from username) but POSTGRES_INITDB_ARGS isn't 

### ISSUE THREAD

**Issue by lowne** [pgautoupgrade/docker-pgautoupgrade#20]
[This](https://github.com/pgautoupgrade/docker-pgautoupgrade/blob/430eb9290dd9aeed421ffeefdb2502b2bec28477/docker-entrypoint.sh#L491) and following lines need to specify dbname as the last argument, because (from [here](https://www.postgresql.org/docs/current/app-postgres.html))

> **database**
> Specifies the name of the database to be accessed. This must be the last argument on the command line. If it is omitted it defaults to the user name.

So, something like:
```bash
COLLATE=$(echo 'SHOW LC_COLLATE' | "${OLDPATH}/bin/postgres" --single -D "${OLD}" "${POSTGRES_DB}" | grep 'lc_collate = "' | cut -d '"' -f 2)
```

**Comment by justinclift** [comment]
Ahhh.  Interesting.

Want to through together a PR that fixes it? :smile:

**Comment by jjb** [comment]
with https://github.com/pgautoupgrade/docker-pgautoupgrade/pull/23 and the below compose config i still get 

```
initdb: error: directory "/var/lib/postgresql/data/pgdata" exists but is not empty
initdb: hint: If you want to create a new database system, either remove or empty the directory "/var/lib/postgresql/data/pgdata" or run initdb with an argument other than "/var/lib/postgresql/data/pgdata".
```

```yaml
  postgres:
    image: 'pgautoupgrade/pgautoupgrade:16-alpine'
    environment:
      POSTGRES_USER: 'redacted'
      POSTGRES_PASSWORD: 'redacted'
      POSTGRES_DB: 'redacted'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432'
```
