### ISSUE TITLE
Healthcheck could break update

### ISSUE THREAD

**Issue by wuast94** [pgautoupgrade/docker-pgautoupgrade#59]
i run this image in a swarm cluster that checks for health and if the container is unhealthy it restarts the container and try to get it running. this will happn in the upgrade process which dont work. 

i used 
```
healthcheck:
    test: [CMD-SHELL, "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    start_period: 20s
    interval: 30s
    retries: 5
    timeout: 5s
```

i think nothing we can do about directly (maybee providing a script that does this healthcheck but will also exit code 0 when an update is running?) but more a think we should mention?
